# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Newswim's Blog
email: ofenixculpa@gmail.com
description: >
  A document that records the charting of characters
logo: "/assets/images/baseball44.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Dan Minshew'
bio: >
  O Felix Culpa!
author_image: "/assets/images/profile.png"
twitter_username: newswim
github_username:  newswim

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
